# Generated by Django 4.2.6 on 2024-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Filing', 'Filing'), ('Answer Complaint', 'Answer Complaint'), ('Discovery', 'Discovery'), ('Response to Discovery', 'Response to Discovery'), ('Judgement', 'Judgement')], default='Filing', max_length=50),
        ),
    ]
