# Generated by Django 5.0.2 on 2024-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_staffreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='created_by',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(default='Court', max_length=100),
            preserve_default=False,
        ),
    ]
