# Generated by Django 5.0.2 on 2024-03-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_approved_alter_case_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='file',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.file'),
            preserve_default=False,
        ),
    ]
