# Generated by Django 5.0.2 on 2024-03-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_allocated_file_case_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file',
        ),
    ]
