# Generated by Django 5.0.2 on 2024-03-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='allocated',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
