# Generated by Django 5.0.2 on 2024-03-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_remove_case_allocated_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='approved',
        ),
    ]
