# Generated by Django 5.0.2 on 2024-03-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_case_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(default='Kitale', max_length=100),
            preserve_default=False,
        ),
    ]
