# Generated by Django 5.0.2 on 2024-03-15 13:35

from datetime import date
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_file_remove_case_approved_remove_case_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cases.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(default='Kitale', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default= date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(default='case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='case_documents/'),
        ),
        migrations.AddField(
            model_name='case',
            name='opponent_client',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_counsel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Filing', 'Filing'), ('Answer Complaint', 'Answer Complaint'), ('Discovery', 'Discovery'), ('Response to Discovery', 'Response to Discovery'), ('Judgement', 'Judgement')], default='Filing', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='updated_cases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
