# Generated by Django 5.0.2 on 2024-03-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_case_approved_case_assigned_to_case_client_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('client', 'title')},
        ),
    ]
