# Generated by Django 5.0.2 on 2024-03-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_accountant_clerk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
