# Generated by Django 5.0.2 on 2024-03-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_case_landed_by_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Sample', max_length=200),
            preserve_default=False,
        ),
    ]
