# Generated by Django 5.0.4 on 2024-04-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
