# Generated by Django 5.0.4 on 2024-04-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_case_is_done_case_is_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_task',
        ),
    ]
