# Generated by Django 5.0.4 on 2024-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_remove_case_is_done_remove_case_is_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
