# Generated by Django 5.0.4 on 2024-04-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_remove_clientfilemanagement_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_task',
        ),
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
