# Generated by Django 5.0.4 on 2024-04-05 01:27

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_remove_case_is_done_remove_case_is_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='documents',
            field=models.FileField(blank=True, null=True, storage=cases.models.CustomFileSystemStorage(), upload_to='case_documents/'),
        ),
    ]
