# Generated by Django 5.0.4 on 2024-04-05 11:05

import cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_file_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case'),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.client'),
        ),
        migrations.AlterField(
            model_name='case',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.case_document_path),
        ),
    ]
