# Generated by Django 5.0.4 on 2024-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_alter_case_updated_by_alter_caseversion_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
